### ISSUE TITLE
Module lỗi trên 4.0.29

### ISSUE THREAD

**Issue by hpleduit** [hoaquynhtim99/events#1]
- Cài đặt không tự động kích hoạt trực tiếp module
- Kích chọn trang chính của module không có giá trị trả về nên trắng trang
- Thêm sự kiện thì phần chủ đề chưa tạo thì nó vẫn không bắt lỗi
- Thêm sự kiện thì phần Liên kết tỉnh không tự động tạo được
- Khi click thêm sự kiện thì không thực hiện được báo lổi trắng trang
  Thấy module hay quá nên cài dùng thử nhưng chưa sử dụng được gì hết. Cảm ơn

**Comment by hoaquynhtim99** [comment]
> Cài đặt không tự động kích hoạt trực tiếp module

Cái này mình không hiểu.
Những lỗi khác bạn check lại giúp, ở những site khác hoặc localhost .... xem có được không, rất nhiều người dùng chưa thấy báo lỗi trầm trọng như vậy
